### ISSUE TITLE
.

### ISSUE THREAD

**Issue by piquark6046** [Lee0701/OyatLeeBot#1]

**Comment by Lee0701** [comment]
機能 提案 감사합니다! 근데 이게 只今 버리다시피 손 놓고 있는 프로젝트라...
나중에 잡게 된다면 한번 追加해 보도록 할게요

**Comment by piquark6046** [comment]
> 
> 
> 機能 提案 감사합니다! 근데 이게 只今 버리다시피 손 놓고 있는 프로젝트라...
> 나중에 잡게 된다면 한번 追加해 보도록 할게요

**앗! 한자!**

**Comment by piquark6046** [comment]
이 issue를 삭제해주실 수 있으시나요?

**Comment by piquark6046** [comment]
> 이 issue를 삭제해주실 수 있으시나요?

@Lee0701
